- README.md
> Add "IJulia is broken" is drama

- README.md
Add PowerShell drama about curl and wget aliases
> PowerShell drama

- README.md
Issue about banning a user that has posted a "phallic" emoji
> Added yet another Nodejs drama

- README.md
resisting powerful urge to @mention all the stargazers ![troll](https://dujrsrsgsd3nh.cloudfront.net/img/emoticons/troll-1414023002.png)
> stargazers beware

- README.md
> I didn't make an issue out of this, you made an issue out of this
> Argon2 debate

- README.md
> Update README.md with VSCode drama

- README.md
96 comments, hundreds of reactions. Dramatic enough?
Also perhaps the links should have a title, e.g.:
---
https://github.com/dotnet/cli/issues/3093 - .NET core should not SPY on users by default
---
I can send a PR to add it to all of them if you'd like.
> Add ".NET core should not SPY on users by default"

- README.md
An entire repository of drama, or just forum drama rehashed on GitHub
> add pfsense-closedsource repo

- README.md
Old, but a good read. There's a lot more of these, but I picked three.
https://github.com/opencart/opencart/issues/3834
https://github.com/opencart/opencart/issues/1534
and
https://github.com/opencart/opencart/issues/1269
> Added OpenCART drama

- README.md
@MikeMcQuaid bans everyone who :-1: his comments.
Source: https://www.reddit.com/r/programmingcirclejerk/comments/8200wl/senior_engineer_at_github_blocks_anyone_who_his/
> Add homebrew drama

- README.md
The two people team have a mess on their hands with this one.
> Critical Linux filesystem permissions changed by npm

- README.md
Add reference to node-cross-spawn PR about removing "nice-try" dependency
> Add reference to node-cross-spawn "nice-try" PR

- README.md
436 comments.
Lots of drama.
Locked.
Merge already :^)
> Add Chinese C# request

- README.md
They intended that adding a Easter egg was a good idea, then got flooded with "hate"(? I'm not sure what is the most appropriate word here).
Just reverted 15 minutes ago 😂🤣 https://github.com/ant-design/ant-design/commit/d648b822a6b2789a783c7ad685a122466f6c083c
> Add ant-design Christmas Easter egg

- README.md
PiotrGrochowski added some new characters to Consolas and put it on github as 'open source software'. Some people disagreed and had a dispute with him.
> Add license dispute on PiotrGrochowski/Consolas

- README.md
> Add the Mastodon link underline thing

- README.md
wow how come I commit in master? O_o
> wow how come I commit in master? O_o

- README.md
Can't believe no one has added this classic of the genre yet.
https://github.com/greatsuspender/thegreatsuspender/issues/1175
See also https://github.com/greatsuspender/thegreatsuspender/issues/1263 and https://github.com/deanoemcke/thegreatdiscarder/issues/40. Blast radius will probably increase in the next few days.
> add "The Great Suspender" Chrome extension hijack drama

- README.md
2 issues of Homebrew-drama were deleted; added archive for those.
Also added a new drama to https://github.com/projecthamster/hamster/issues/574
> 2 archive, one drama

- README.md
Add minor drama about a vulnerability that doesn't exist. The developer was very respectful and well-reasoned but the guy kept going in a circular argument that boiled down to "this library uses pickle, therefore it's vulnerable".
"If you write a malicious class and then call an internal library function that happens to call pickle, pickle will call a function in your malicious class."
https://tomforb.es/cve-2022-0329-and-the-problems-with-automated-vulnerability-management/
> Add minor drama about a vulnerability that doesn't exist

- README.md
Complaining about someone using masscan to mass scan their network
"Some idiot is using your tool to mass scan our network"
ez link: https://github.com/robertdavidgraham/masscan/issues/482
> Added masscan issue
